### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bejgumshirisha** [amatiasq/vsc-sort-imports#62] opened 2019-12-16 13:09 UTC
- Issue Type: `Performance`
- Extension Name: `sort-imports`
- Extension Version: `6.1.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/surendra/amatiasq.sort-imports-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by amatiasq** [comment] 2020-05-29 12:10
Duplicate of #59

**Closed by amatiasq** 2020-05-29 12:10 UTC
