### ISSUE TITLE
Cursor jumps to end of file

### ISSUE THREAD

**Issue by sQVe** [amatiasq/vsc-sort-imports#7] opened 2017-11-15 16:02 UTC
![sort-import-bug](https://user-images.githubusercontent.com/2284724/32846122-b00895c8-ca26-11e7-8a1b-f6eb512177c8.gif)

If I use `"sort-imports.on-save": true` my cursor jumps to the bottom of the file on each save. This is incredibly annoying and has forced me to leave *format on save* and opt for a key bind instead.

I've disabled all other formatting related extensions and the issue still occurs when `sort-imports` is enabled. Give me a ping if you need further information, I'm happy to help.

**Comment by amatiasq** [comment] 2017-11-15 17:15
This is weird, I use that feature too but I haven't experienced this issue before, if you set it to false it does not happen? I didn't understood that part.

In any case, version of visual studio you're using would be helpful.

**Comment by adriantoine** [comment] 2017-11-15 17:45
Hello,
I have the same issue, I use the latest version of VS Code (`1.18.0`).

**Comment by jessejanderson** [comment] 2017-11-15 20:06
Same issue here, I also use Prettier which doesn't have this issue. I'm also on the latest version of VS Code (`1.18.0`).

**Comment by sQVe** [comment] 2017-11-15 21:02
I'm running `Version         : 1.18.0-3`. I cannot replicate this issue when triggering sort via a `Ctrl + Shift + P+ or a keybind.

**Comment by amatiasq** [comment] 2017-11-16 15:02
Yep, I can reproduce the issue now, it happens to me since VSCode updated. I'll try to debug it but I haven't much time, any help would be appreciated here.

**Comment by wshaver** [comment] 2017-12-05 17:53
I'm also hitting this. Was hitting it in the other deprecated sort imports, swapped to this one, still seeing it.

**Comment by peterjuras** [comment] 2017-12-08 14:32
If my old (deprecated) extension also shows this behavior then there might have been an update in the behavior of Visual Studio Code with one of the new versions. I'm also seeing this sadly :/

**Comment by gurgeous** [comment] 2017-12-29 18:53
Seeing it too.

**Comment by sledorze** [comment] 2018-01-12 10:54
Same problem here...

**Comment by CentaurWarchief** [comment] 2018-01-31 01:09
Same here :(

**Comment by amatiasq** [comment] 2018-01-31 09:32
Yeah, I still have this issue and it's getting annoying, no change was made lately so it's probably a new Visual Studio version as @peterjuras says so I don't know where to start to fix it.

BTW guys, you can just add a +1 to the first post in this thread. We don't want to clutter it with "me too" messages so it will be easier to spot the important information to solve this bug.

**Comment by jessejanderson** [comment] 2018-02-06 17:50
Any update for this? It's been 3 months now and I'd love to be able to use this plugin again. In its current state it's unusable.

**Comment by amatiasq** [comment] 2018-02-06 18:08
The last update is the one I wrote last week, the previous comment.

I still using the plugin, it's annoying but I can live with it. For me it's way better than sorting imports manually.

If you find time to fix the issue with a PR we'll be more than happy to finally close it.

**Comment by dorian-marchal** [comment] 2018-02-06 23:49
Same here.

**Comment by dorian-marchal** [comment] 2018-02-09 21:23
[This comment](https://github.com/Microsoft/vscode/issues/38728#issuecomment-347794326) explain the "right" way to format a document: 

> @Stijnkool The recommendation is to register a format provider for the language. Then, when users configure editor.formatOnSave to true, your format provider will be invoked for the text document that will be saved. Then, the edits you return will be diffed against the current text, and a minimal set of edits will be computed and applied. Thus, if your formatter gives a replace-entire-file with new content edit, the edit will be broken up and markers (including the cursor) will survive.

I don't know if this is what this extension do.

**Comment by amatiasq** [comment] 2018-02-09 23:38
That's exactly not what this library is doing. Thanks @dorian-marchal , I'll try that on Monday 👍

**Comment by amatiasq** [comment] 2018-02-12 18:13
I'm looking how this extension can register as a Document Formatter Provider but as the operations are made by `import-sort` it returns a [`ICodeChange[]`](https://github.com/renke/import-sort/blob/master/packages/import-sort/src/index.ts#L16-L21) and VSCode expects a [`TextEdit[]`](https://github.com/Microsoft/vscode-languageserver-node/blob/master/types/src/main.ts#L293-L308) which is quite different.

I've pushed the progress into [a branch](https://github.com/amatiasq/vsc-sort-imports/tree/cursor-jumps-eof-fix) in case you want to take a look at it.

Will probably resume it in a few days.

**Comment by vshab** [comment] 2018-02-14 21:26
@amatiasq I think making thing extension as formatter can be not the best idea right now because vscode doesn't allow to have multiple formatters simultaneously:
https://github.com/Microsoft/vscode/issues/33477
https://github.com/Microsoft/vscode/issues/41882

This means user would have to choose for JS between sort-imports and prettier for example...

**Comment by amatiasq** [comment] 2018-02-15 13:49
Yeah, that changes the situation, I assumed formatters would run sequentially. I guess the branch is garbage now.

**Comment by OliverJAsh** [comment] 2018-03-15 19:08
Is there any way to run Prettier and import-sort in a single command?

**Comment by sQVe** [comment] 2018-03-15 19:10
@OliverJAsh How is that related to this issue?

**Comment by OliverJAsh** [comment] 2018-03-15 19:11
@sQVe I was linked here from #15 and there's talk of how multiple formatters work in VSCode.

**Comment by amatiasq** [comment] 2018-03-18 19:33
The relation is than we were discussing about making `import-sort` a formatter here.

The question is indeed unrelated, and in any case the answer is no, `import-sort` is not related to Prettier in any way so there is no command to run both.

**Comment by amatiasq** [comment] 2018-07-31 15:50
This issue comes from an update in VSCode, I've been researching it but haven't been able to find how to stop it. I'm still using the plugin to be honest, the benefit it brings to my projects is bigger than the inconvenience caused by this issue to me.

Any help with this issue is welcome.

**Comment by amatiasq** [comment] 2018-10-23 08:35
@two-bridges that's a good point, I'll add it to the README.

If you can debug it I'll be glad, I couldn't find the source for this issue and can't spend more time on it.

About the keybinding, I don't use it at all, I have `sort-imports.on-save` enabled.

**Comment by two-bridges** [comment] 2018-10-23 08:55
cool @amatiasq.  I'll take a look in the next few days on a quiet evening

**Comment by amatiasq** [comment] 2018-11-02 10:36
@two-bridges Did you find time to check it? is there something I can do to help you?

**Comment by jansav** [comment] 2018-12-14 10:58
I've tried to this this issue with PR #34.

**Closed** 2018-12-18 11:04 UTC
Labels: bug, help wanted
